### PR TITLE
https for patchbot

### PR DESCRIPTION
**Pull request by fchapoton**
and remove old png icon (now svg)

### CODE REVIEW

**Comment by fchapoton** [comment]
The icons should call patchbot via https. And there is a superfluous icon.

**Comment by fchapoton** [comment]
ping ?

**Comment by fchapoton** [comment]
hello ? this prevents the trac website to be correctly secured !

**Comment by embray** [comment]
Apparently I wasn't subscribed to notifications for this repo.

**Comment by embray** [comment]
Thanks, I'll install the new version in a bit.  I also need to update the plugin to properly work around the Trac issue of not allowing usernames with dots in them.

**Pull request merged**
